name: Build Android APKs (Lite & Pro)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - "**.kv"
      - "buildozer-*.spec"
      - ".github/workflows/android-kivy-matrix.yml"
      - "sample_inventory.csv"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        edition: [ lite, pro ]
        include:
          - edition: lite
            spec: buildozer-lite.spec
            main: main_lite.py
            artifact: MyPocketPOS-Lite-debug-apk
          - edition: pro
            spec: buildozer-pro.spec
            main: main_pro.py
            artifact: MyPocketPOS-Pro-debug-apk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip openjdk-17-jdk python3-pip python3-venv \
            libffi-dev libssl-dev libsqlite3-dev libbz2-dev libreadline-dev zlib1g-dev \
            libncurses5 libtinfo5 liblzma-dev

      - name: Install Buildozer & Cython
        run: |
          python -m pip install --upgrade pip wheel
          pip install Cython==0.29.37 virtualenv
          pip install buildozer==1.5.0

      - name: Install Android SDK / Build tools
        shell: bash
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk
          cd ~/.buildozer/android/platform/android-sdk

          echo "Downloading Android command line tools..."
          # retry download if Google's server times out
          for i in {1..3}; do
            echo "Attempt $i to download SDK tools..."
            wget -q --show-progress --tries=3 --timeout=30 \
              https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip \
              -O cmdtools.zip && break || sleep 15
          done

          if [ ! -f cmdtools.zip ]; then
            echo "Download failed after 3 attempts."
            exit 1
          fi

          echo "Unzipping SDK tools..."
          unzip -q cmdtools.zip -d cmdline-tools

          echo "Accepting licenses..."
          yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses

          echo "Installing Android 33 + build-tools..."
          yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
            "platforms;android-33" \
            "build-tools;34.0.0" \
            "platform-tools"

          echo "$HOME/.buildozer/android/platform/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH
      - name: Build debug APK
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: bin/*.apk
          retention-days: 7
