name: Build My Pocket POS (Lite)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms & tools
        run: |
          sdkmanager --install "platforms;android-33" "build-tools;33.0.2" "platform-tools" "ndk;25.1.8937393"
          yes | sdkmanager --licenses

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 Cython==0.29.36

      - name: Build debug APK
        env:
          ANDROIDSDK: ${{ env.ANDROID_SDK_ROOT }}
          ANDROIDNDK: ${{ env.ANDROID_SDK_ROOT }}/ndk/25.1.8937393
          ANDROIDAPI: "33"
          ANDROIDMINAPI: "24"
        run: |
          echo "Starting Buildozer build…"
          buildozer android debug --verbose

      - name: Upload APK
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: MyPocketPOSLite-debug
          path: |
            bin/*.apk
            bin/*.aab
          if-no-files-found: warn
